### ISSUE TITLE
インストールできない。

### ISSUE THREAD

**Issue by johna1203** [suguru/elasticsearch-analysis-japanese#1]
elasticsearch-1.2.1 を使っておりますがインストールできませんでした。

$bin/plugin -install suguru/elasticsearch-analysis-japanese
-> Installing suguru/elasticsearch-analysis-japanese...
Trying https://github.com/suguru/elasticsearch-analysis-japanese/archive/master.zip...
^Cjohna@johna-deb:~/Downloads/elasticsearch-1.2.1$ bin/plugin -install suguru/elasticsearch-analysis-japanese/1.1.0
-> Installing suguru/elasticsearch-analysis-japanese/1.1.0...
Trying http://download.elasticsearch.org/suguru/elasticsearch-analysis-japanese/elasticsearch-analysis-japanese-1.1.0.zip...
Trying http://search.maven.org/remotecontent?filepath=suguru/elasticsearch-analysis-japanese/1.1.0/elasticsearch-analysis-japanese-1.1.0.zip...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/suguru/elasticsearch-analysis-japanese/1.1.0/elasticsearch-analysis-japanese-1.1.0.zip...
Trying https://github.com/suguru/elasticsearch-analysis-japanese/archive/v1.1.0.zip...
Trying https://github.com/suguru/elasticsearch-analysis-japanese/archive/master.zip...
Downloading ...................................................DONE
Installed suguru/elasticsearch-analysis-japanese/1.1.0 into /home/johna/Downloads/elasticsearch-1.2.1/plugins/analysis-japanese
Usage:
    -u, --url     [plugin location]   : Set exact URL to download the plugin from
    -i, --install [plugin name]       : Downloads and installs listed plugins [*]
    -t, --timeout [duration]          : Timeout setting: 30s, 1m, 1h... (infinite by default)
    -r, --remove  [plugin name]       : Removes listed plugins
    -l, --list                        : List installed plugins
    -v, --verbose                     : Prints verbose messages
    -s, --silent                      : Run in silent mode
    -h, --help                        : Prints this help message

 [*] Plugin name could be:
     elasticsearch/plugin/version for official elasticsearch plugins (download from download.elasticsearch.org)
     groupId/artifactId/version   for community plugins (download from maven central or oss sonatype)
     username/repository          for site plugins (download from github master)

Message:
   Error while installing plugin, reason: IllegalArgumentException: Plugin installation assumed to be site plugin, but contains source code, aborting installation.

**Comment by suguru** [comment]
日本語解析には、オフィシャルプラグインを使うことをお勧めします。It is recommended to use official kuromoji plugin to analyze Japanese text.

https://github.com/elasticsearch/elasticsearch-analysis-kuromoji

Since official plugin is released, I will not support this plugin.

**Comment by johna1203** [comment]
なるほど。
回答ありがとうございます。
私が勘違いしていました、Kuromojiのプラスアルファかと思っていました。
